### ISSUE TITLE
ClasspathScanner fails with NoClassDefFoundErrors when running under JDK11

### ISSUE THREAD

**Issue by TGNThump** [kbss-cvut/jb4jsonld#18]
Both the maven builds for this project and downstream projects fail as a result of failing tests without SCAN_PACKAGE set when running using JDK11.

**Comment by ledsoft** [comment]
Hey, thanks for the report. This issue is due to the multi-release JAR structure introduced in Java 9. I'll look into it ASAP.

**Comment by ledsoft** [comment]
Fixed in 0.6.0.
