### ISSUE TITLE
Handling Language Indexing

### ISSUE THREAD

**Issue by TGNThump** [kbss-cvut/jb4jsonld#20]
It would be great to be able to translate jsonld language map fields defined with [Language Indexing](https://json-ld.org/spec/latest/json-ld/#language-indexing).

I'm not sure what the best way to handle this would be with regards to the Java mappings though.

**Comment by ledsoft** [comment]
Hi,

yeah, this has been on my backlog for [JOPA](https://github.com/kbss-cvut/jopa) (JB4JSON-LD uses JOPA object model annotations) for some time, as we need multi-lingual attributes there, too.
The plan is to introduce a value object type which would contain the language-tagged values (probably a `Map` wrapped in some convenient API). Once this is done in JOPA, it can be implemented here as well.
There's an [issue](https://github.com/kbss-cvut/jopa/issues/59) tracking it in jOPA, I'll use this one to track it here.

**Comment by ledsoft** [comment]
Implemented in 0.8.0. Feel free to give it a try and provide feedback. Will try to put up some documentation into Wiki.

**Comment by TGNThump** [comment]
Looks good to me! Thanks.
