### ISSUE TITLE
Relaxing check about single cardinality constraints in json deserialization DefaultInstanceBuilder)

### ISSUE THREAD

**Issue by cristianolongo** [kbss-cvut/jb4jsonld#24]
Le `C` be an OWL class which defines an single value cardinality constraint (cardinality==1) on some property `p`.
Now let `i` be an individual of class `C`, which occurs two times in a json file so that in both the occurrences the property `p` is present, with values respectively `o` and `o'`.  When the `DefaultInstanceBuilder` encounter the second occurrence of `i` during the parsing of the json file, it throws a `JsonDeserializationException` :-1: 

> Encountered multiple values of property

However, if `o` and `o'` are _equals_ the single value constraint is not actually violated. In such a cases I think that avoiding to throw the exception would make the api more robust against _strang_ but correct json files.

**Comment by ledsoft** [comment]
Makes sense, thanks for the PR!

**Comment by ledsoft** [comment]
In 0.6.0.
