### ISSUE TITLE
NoClassDefFoundError: cz/cvut/kbss/jopa/model/MultilingualString on version 0.8.2

### ISSUE THREAD

**Issue by cristianolongo** [kbss-cvut/jb4jsonld#29]
Using cz.cvut.kbss.jsonld.jackson.JsonLdModule.JsonLdModule to configure the jackson object mapper in a spring boot application i got the following error

> java.lang.NoClassDefFoundError: cz/cvut/kbss/jopa/model/MultilingualString
> 	cz.cvut.kbss.jsonld.deserialization.DefaultInstanceBuilder.openCollection(DefaultInstanceBuilder.java:156)
> 	cz.cvut.kbss.jsonld.deserialization.expanded.CollectionDeserializer.processValue(CollectionDeserializer.java:48)
> 	cz.cvut.kbss.jsonld.deserialization.expanded.ObjectDeserializer.processValue(ObjectDeserializer.java:57)
> 	cz.cvut.kbss.jsonld.deserialization.expanded.ExpandedJsonLdDeserializer.deserialize(ExpandedJsonLdDeserializer.java:51)
> 	cz.cvut.kbss.jsonld.jackson.deserialization.JacksonJsonLdDeserializer.deserialize(JacksonJsonLdDeserializer.java:62)
> 	com.fasterxml.jackson.databind.deser.std.ObjectArrayDeserializer.deserialize(ObjectArrayDeserializer.java:195)
> 	com.fasterxml.jackson.databind.deser.std.ObjectArrayDeserializer.deserialize(ObjectArrayDeserializer.java:21)
> 	com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:4218)
> 	com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3267)
> 	org.springframework.http.converter.json.AbstractJackson2HttpMessageConverter.readJavaType(AbstractJackson2HttpMessageConverter.java:239)
> 	org.springframework.http.converter.json.AbstractJackson2HttpMessageConverter.read(AbstractJackson2HttpMessageConverter.java:227)
> 	org.springframework.web.client.HttpMessageConverterExtractor.extractData(HttpMessageConverterExtractor.java:104)
> 	org.springframework.web.client.RestTemplate$ResponseEntityResponseExtractor.extractData(RestTemplate.java:998)
> 	org.springframework.web.client.RestTemplate$ResponseEntityResponseExtractor.extractData(RestTemplate.java:981)
> 	org.springframework.web.client.RestTemplate.doExecute(RestTemplate.java:741)
> 	org.springframework.web.client.RestTemplate.execute(RestTemplate.java:714)
> 	org.springframework.web.client.RestTemplate.exchange(RestTemplate.java:602)

I just included 

> 		<dependency>
> 			<groupId>cz.cvut.kbss.jsonld</groupId>
> 			<artifactId>jb4jsonld-jackson</artifactId>
> 			<version>0.8.2</version>
> 		</dependency>
> 

May be i need to import some other jopa module?

**Comment by cristianolongo** [comment]
with jb4jsonld-jackson 0.7.0 this does not happen

**Comment by ledsoft** [comment]
Are you by any chance using JOPA separately from JB4JSON-LD? This seems like a conflict of dependency versions, since `MultilingualString` has been added to JOPA API in version 0.15.0 (used by JB4JSON-LD 0.7.1).

**Comment by cristianolongo** [comment]
yes thanks I imported also ontodriver-sesame 0.14

**Comment by ledsoft** [comment]
Ok, closing as invalid.
