### ISSUE TITLE
java2jsonld serialization handles references to node objects incorrectly

### ISSUE THREAD

**Issue by blcham** [kbss-cvut/jb4jsonld#3]
If java object model contains more than one reference to the same java object it is serialized into json-ld incorrectly:

- first reference of the java object is serialized into the json-ld object node, where content of whole java object is serialized e.g.:{
```
{
    "http://onto.fel.cvut.cz/ontologies/documentation/has_related_question" : {
      "@id": "http://onto.fel.cvut.cz/1-q",
      "@type": "http://onto.fel.cvut.cz/ontologies/documentation/question"
    }
}
```
- any subsequent reference to the java object is serialized using "string" property (**!!! this is incorrect !!!**) e.g. :
```
{
   "http://onto.fel.cvut.cz/ontologies/documentation/has_related_question" : "http://onto.fel.cvut.cz/1-q"
}
```

From such document it is inferred by a json-ld processor, that subsequent references refers to string "http://onto.fel.cvut.cz/1-q", not IRI <http://onto.fel.cvut.cz/1-q>.

**To fix this issue there are 2 possible solutions:**

1. jsonld can be extended with a context that defines relevant properties values of type "@id", thus we could fix the example by adding: 
```
{
  "@context": {
    "http://onto.fel.cvut.cz/ontologies/documentation/has_related_question" : { 
       "@id" : "http://onto.fel.cvut.cz/ontologies/documentation/has_related_question", 
       "@type" : "@id"        
    }
  },    
  "@graph": [
    {
.....
```

2. references must be explicitly defined as references to object nodes, i.e. w.r.t. the example it would be:
```
{
 "http://onto.fel.cvut.cz/ontologies/documentation/has_related_question": [
      {
        "@id": "http://onto.fel.cvut.cz/871-q"
      }
  ....
```

**Comment by blcham** [comment]
A related discussion can be found here:
https://github.com/json-ld/json-ld.org/issues/169

**Comment by blcham** [comment]
The related example in json-ld playground:
[json-ld example with context](https://json-ld.org/playground/?startTab=tab-expanded&json-ld=%7B%22%40context%22%3A%7B%22http%3A%2F%2Fonto.fel.cvut.cz%2Fontologies%2Fdocumentation%2Fhas_related_question%22%3A%7B%22%40id%22%3A%22http%3A%2F%2Fonto.fel.cvut.cz%2Fontologies%2Fdocumentation%2Fhas_related_question%22%2C%22%40type%22%3A%22%40id%22%7D%7D%2C%22%40graph%22%3A%7B%22%40id%22%3A%22http%3A%2F%2Fonto.fel.cvut.cz%2Fc7c-q%22%2C%22http%3A%2F%2Fonto.fel.cvut.cz%2Fontologies%2Fdocumentation%2Fhas_related_question%22%3A%22http%3A%2F%2Fonto.fel.cvut.cz%2F871-q%22%7D%7D&context=%7B%7D)

**Comment by ledsoft** [comment]
Ok. I would go with option 2, because 1 to me implies that nothing else than id references can be values of the declared property, which feels too restrictive.

**Comment by blcham** [comment]
Option 1 does not imply that to me, but there is no such issue for "option 2", so i agree.

**Comment by ledsoft** [comment]
[0.2.0]
