### ISSUE TITLE
jsonld2java should support blank nodes

### ISSUE THREAD

**Issue by blcham** [kbss-cvut/jb4jsonld#6]
jsonld2java transformation generates exception if input jsonld document has a blank node. The exception is due to failed attempt to transform blank node to an URI (i assume it from the stack trace that  i saw). Although i did not try it on this data, in text below i created 2 examples of semantically same jsonld document. First one should succeed in transformation while second one i believe would not ... 

First, jsonld document that i think would work:
```
{
  "http://example.org/property" : "value",
  "http://example.org/property2" : {
  	"http://example.org/inner-property" : "otherValue"
   }
}
```

If i transform previous jsonld document using jsonld transformation "flattened", i will get equivalent jsonld document which i believe would fail within jsonld2java transformation:
```
{
  "@graph": [
    {
      "@id": "_:b0",
      "http://example.org/property": "value",
      "http://example.org/property2": {
        "@id": "_:b1"
      }
    },
    {
      "@id": "_:b1",
      "http://example.org/inner-property": "otherValue"
    }
  ]
}
```

Workaround in this case would be removing all "@id" properties, since all of the objects are referenced only once. This is however not general case..

Link to the example in [jsonld playground](https://json-ld.org/playground/#startTab=tab-flattened&json-ld=%7B%22http%3A%2F%2Fexample.org%2Fproperty%22%3A%22value%22%2C%22http%3A%2F%2Fexample.org%2Fproperty2%22%3A%7B%22http%3A%2F%2Fexample.org%2Finner-property%22%3A%22otherValue%22%7D%7D&context=%7B%7D).

**Comment by YanDoroshenko** [comment]
Example jsonld.

[jsonld.txt](https://github.com/kbss-cvut/jb4jsonld/files/1713236/jsonld.txt)

**Comment by ledsoft** [comment]
Done in 0.2.1.
